### PR TITLE
Prog bundle - fix #88

### LINKED ISSUE #88: New Record superclass breaks testers.
ucb-bar/chisel3@2e6444cc55b54b59f781a14823e219d9a2413f72 causes:

    [error] .../ucb-bar/chisel-testers/src/main/scala/chisel3/iotesters/OrderedDecoupledHWIOTester.scala:394: type mismatch;
    [error]  found   : chisel3.core.Record
    [error]  required: chisel3.Bundle
    [error]     (which expands to)  chisel3.core.Bundle
    [error]     io_info = new IOAccessor(device_under_test.io)
    [error]                                                ^
    [error] .../ucb-bar/chisel-testers/src/main/scala/chisel3/iotesters/SteppedHWIOTester.scala:172: type mismatch;
    [error]  found   : chisel3.core.Record
    [error]  required: chisel3.Bundle
    [error]     (which expands to)  chisel3.core.Bundle
    [error]     io_info = new IOAccessor(device_under_test.io)

### PR DESCRIPTION
**Pull request by ucbjrl**
This adds support for `Record` as a super-class of `Bundle` for `Module.io`

NOTE - This includes #89 in order to facilitate testing.

### CODE REVIEW

**Comment by chick** [comment]
@jackkoenig I'm a little concerned about the fact that these changes are required.  I thought the Record/Bundle changes would be more transparent.  But I'd rather get stuff out there and figure out if there's other problems

**Comment by jackkoenig** [comment]
I'm not sure what you mean by the changes being more transparent, but the purpose of Record was to change the type hierarchy of Bundle such that it is now a more specialized case of a more general thing (ie. a Bundle is simply a Record that automatically populates the elements via reflection and attempts to implement cloneType automagically). I'm not sure if there could have been any other way to do it.

**Comment by chick** [comment]
I should have said less API changing, but then again chisel-testers is kind of a special case when it comes to API usage.  I'm for moving forward

**Comment by jackkoenig** [comment]
I see, yeah. Unfortunately, the very nature of Record is API changing so there wasn't much of a choice :(

**Pull request merged**
